ChatRoom/urls.py
from django.apps import apps
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('', RedirectView.as_view(pattern_name="chat:index"), name="root"),
]


if apps.is_installed("debug_toolbar"):
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
]

chat/urls.py
from django.urls import path
from chat import views

app_name = "chat"

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.room_new, name="room_new"),
    path("<str:room_pk>/chat/", views.room_chat, name="room_chat"),
    path("<str:room_pk>/delete/", views.room_delete, name="room_delete"),
    path("<int:room_pk>/users/", views.room_users, name="room_users"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    pass

chat/models.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.db import models
from django.db.models.signals import post_delete

from accounts.models import User 
from ChatRoom.json_extended import ExtendedJSONEncoder, ExtendedJSONDecoder


class OnlineUserMixin(models.Model):
    class Meta:
        abstract = True

    online_user_set = models.ManyToManyField(
        User,
        through="RoomMember",
        blank=True,
        related_name="joined_room_set",
    )

    def get_online_users(self):
        return self.online_user_set.all()
    
    def get_online_usernames(self):
        qs = self.get_online_users().values_list("username", flat=True)
        return list(qs)
    
    def is_joined_user(self, user):
        return self.get_online_users().filter(pk=user.pk).exists()
    
    def user_join(self, channel_name, user):
        try:
            room_member = RoomMember.objects.get(room=self, user=user)
        except RoomMember.DoesNotExist:
            room_member = RoomMember(room=self, user=user)
        is_new_join = len(room_member.channel_names) == 0
        room_member.channel_names.add(channel_name)
        if room_member.pk is None:
            room_member.save()
        else:
            room_member.save(update_fields=["channel_names"])
        return is_new_join
    
    def user_leave(self, channel_name, user):
        try:
            room_member = RoomMember.objects.get(room=self, user=user)
        except RoomMember.DoesNotExist:
            return True
        room_member.channel_names.remove(channel_name)
        if not room_member.channel_names:
            room_member.delete()
            return True
        else:
            room_member.save(update_fields=["channel_names"])
            return False
        

class Room(OnlineUserMixin, models.Model):
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owned_room_set")

    class Meta:
        ordering = ["-pk"]

    @property
    def chat_group_name(self):
        return self.make_chat_group_name(room=self)
    
    @staticmethod
    def make_chat_group_name(room=None, room_pk=None):
        return "chat-%s" % (room_pk or room.pk)
    


def room__on_post_delete(instance: Room, **kwargs):
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        instance.chat_group_name,
        {
            "type": "chat.room.deleted",
        }
    )


post_delete.connect(
    room__on_post_delete,
    sender=Room,
    dispatch_uid="room__on_post_delete",
)


class RoomMember(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    channel_names = models.JSONField(
        default=set,
        encoder=ExtendedJSONEncoder,
        decoder=ExtendedJSONDecoder,
    )

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User

class SignupForm(UserCreationForm):
   class Meta(UserCreationForm.Meta):
       model = User
       fields = ['username', 'email', 'first_name', 'last_name']

chat/forms.py
from django import forms
from chat.models import Room


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ["name"]

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView

from django.urls import reverse_lazy

from django.views.generic import TemplateView, CreateView
from accounts.models import User
from accounts.forms import SignupForm


signup = CreateView.as_view(
    model=User,
    form_class=SignupForm,
    template_name="partials/form.html",
    extra_context={
        "form_name": "회원가입",
        "submit_label": "회원가입",
    },
    success_url=reverse_lazy("accounts:login"),
)


login = LoginView.as_view(
    template_name="partials/form.html",
    extra_context={
        "form_name": "로그인",
        "submit_label": "로그인",
    },
)

logout = LogoutView.as_view(
    next_page="accounts:login",
)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"


profile = ProfileView.as_view()

chat/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from chat.forms import RoomForm
from chat.models import Room

def index(request):
    room_qs = Room.objects.all()
    return render(request, "chat/index.html", {
        "room_list": room_qs,
    })


@login_required
def room_new(request):
    if request.method == "POST":
        form = RoomForm(request.POST)
        if form.is_valid():
            created_room = form.save(commit=False)
            created_room.owner = request.user
            created_room.save()
            return redirect("chat:room_chat", created_room.pk)
    else:
        form = RoomForm()
    return render(request, "chat/room_form.html", {
        "form": form,
    })


@login_required
def room_chat(request, room_pk):
    room = get_object_or_404(Room, pk=room_pk)
    return render(request, "chat/room_chat.html", {
        "room": room,
    })


@login_required
def room_delete(request, room_pk):
    room = get_object_or_404(Room, pk=room_pk)

    if room.owner != request.user:
        messages.error(request, "채팅방 소유자가 아닙니다.")
        return redirect("chat:index")
    
    if request.method == "POST":
        room.delete()
        messages.success(request, "채팅방을 삭제했습니다.")
        return redirect("chat:index")
    
    return render(request, "chat/room_confirm_delete.html", {
        "room": room,
    })


@login_required
def room_users(request, room_pk):
    room = get_object_or_404(Room, pk=room_pk)

    if not room.is_joined_user(request.user):
        return HttpResponse("Unauthorized user", status=401)
    
    username_list = room.get_online_usernames()
    return JsonResponse({
        "username_list": username_list,
    })

ChatRoom/templates/base.html
{% load django_bootstrap5 %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Chan's channels</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% block extra-style %}{% endblock %}
</head>
<body>

<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            Chan's Chatting
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="#" class="nav-link px-2 link-secondary">채팅</a></li>
        </ul>

        <div class="col-md-3 text-end">
            {% if not user.is_authenticated %}
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary me-2">로그인</a>
                <a href="{% url 'accounts:signup' %}" class="btn btn-primary">회원가입</a>
            {% else %}
                <a href="{% url 'accounts:profile' %}" class="btn btn-outline-primary me-2">프로필</a>
                <a href="{% url 'accounts:logout' %}" class="btn btn-primary">로그아웃</a>
            {% endif %}
        </div>
    </header>

    {% bootstrap_messages %}

    {% block content %}{% endblock %}
</div>

{% block extra-script %}{% endblock %}

</body>
</html>

ChatRoom/templates/partials/form.html
{% extends "base.html" %}
{% load django_bootstrap5 %}

{% block content %}
    <h3>{{ form_name }}</h3>

    <div class="card">
        {% if form_name %}
            <div class="card-header">{{ form_name }}</div>
        {% endif %}
        <div class="card-body">
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary"
                       {% if submit_label %}value="{{ submit_label }}"{% endif %} />
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}

{% block content %}
    <h2>{{ user.username }}'s 프로필</h2>

    <ul>
        <li>username: {{ user.username }}</li>
        <li>last_login: {{ user.last_login }}</li>
    </ul>
{% endblock %}

chat/templates/chat/base.html
{% extends "base.html" %}

chat/templates/chat/index.html
{% extends "chat/base.html" %}

{% block content %}
    <h1>채팅방 목록</h1>
    <ul>
        {% for room in room_list %}
            <li>
                <a href="{% url 'chat:room_chat' room.pk %}">
                    {{ room.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'chat:room_new' %}">
        새 채팅방 만들기
    </a>
{% endblock %}

chat/templates/chat/room_chat.html
{% extends "chat/base.html" %}

{% block extra-style %}
<style>
.chat-message > div {
    background-color: #3b3b3b;
    color: #e1e1e1;
    border-radius: 0.8em;
    padding: 0.4em;
    margin: 0.4em 0;
    display: inline-block;
    white-space: pre-wrap;
    max-width: 80%;
    word-wrap: break-word;
}
.chat-message.me {
    text-align: right;
}
.chat-message.me > div {
    background-color: #1f8cff;
    color: #fff;
    text-align: left;
}
</style>
{% endblock %}

{% block content %}
    {# TODO: 웹소켓으로 실시간 채팅 기능 구현하기 #}

    <div class="container my-5">
        <div class="row">
            <div class="col-sm-8">
                <div class="card" style="height: 600px;">
                    <div class="card-header">
                        채팅방 : {{ room.name }}
                    </div>
                    <div class="card-body overflow-hidden">
                        <div id="chat_messages" class="w-100 h-100 border-0 overflow-scroll"></div>
                    </div>
                    <div class="card-footer">
                        <form id="message_form">
                            <input type="text" name="message" class="form-control"
                                   autofocus autocomplete="off" />
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="card" style="height: 600px;">
                    <div class="card-header">
                        접속 유저 <span id="user_count"></span>
                    </div>
                    <div class="card-body">
                        <ul id="user_list"></ul>
                    </div>
                </div>
            </div>

            <hr class="my-3" />

            <a href="{% url 'chat:index' %}" class="btn btn-primary">대기실로 이동</a>

            {% if request.user == room.owner %}
                <a href="{% url 'chat:room_delete' room.pk %}" class="btn btn-danger">
                    채팅방 삭제하기
                </a>
            {% endif %}
        </div>
    </div>

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">알림</h5>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">OK</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra-script %}
<script>
const handlers = {
    chat_messages_tag: null,
    ws: null,
    retry: 0,
    username_set: new Set(),

    init() {
        this.chat_messages_tag = document.querySelector("#chat_messages");
        document.querySelector("#message_form")
            .addEventListener("submit", this.onsubmit.bind(this));
    },
    connect(ws_url) {
        if(this.ws) this.ws.close();

        this.ws = new WebSocket(ws_url || this.ws?.url);

        this.ws.onopen = this.onopen.bind(this);
        this.ws.onclose = this.onclose.bind(this);
        this.ws.onerror = this.onerror.bind(this);
        this.ws.onmessage = this.onmessage.bind(this);
    },
    reconnect() {
        this.connect();
    },
    onopen() {
        console.log("웹소켓 서버와 접속");
        this.retry = 0;

        fetch('{% url "chat:room_users" room.pk %}')
            .then(response => response.json())
            .then(({ username_list }) => {
                this.username_set = new Set([...this.username_set, ...username_list]);
                this.update_user_list();
            });
    },
    onclose(event) {
        const close_code = event.code;

        if(close_code === 4000) {
            this.modal("채팅방이 삭제되었습니다. 대기실로 이동합니다.", () => {
                window.location.href = "{% url 'chat:index' %}";
            });
        }
        else if(!event.wasClean) {
            console.error("웹소켓 서버가 죽었거나, 네트워크 장애입니다.");
            if(this.retry < 3) {
                this.retry += 1;
                setTimeout(() => {
                    this.reconnect();
                    console.log(`[${this.retry}] 접속 재시도 ...`);
                }, 1000 * this.retry)
            }
            else {
                console.log("웹소켓 서버에 접속할 수 없습니다. 대기실로 이동합니다.");
                window.location.href = "{% url 'chat:index' %}";
            }
        }
    },
    onerror() {
        console.log("웹소켓 에러가 발생했습니다. 대기실로 이동합니다.");
        window.location.href = "{% url 'chat:index' %}";
    },
    onmessage(event) {
        const message_json = event.data;
        console.log("메세지 수신 :", message_json);

        const { type, message, sender, username } = JSON.parse(message_json);
        switch(type) {
            case "chat.message":
                this.append_message(message, sender);
                break;
            case "chat.user.join":
                this.append_message(`${username}님이 들어오셨습니다.`);
                this.username_set.add(username);
                this.update_user_list();
                break;
            case "chat.user.leave":
                this.append_message(`${username}님이 나가셨습니다.`);
                this.username_set.delete(username);
                this.update_user_list();
                break;
            default:
                console.error(`Invalid message type : ${type}`);
        }
    },
    append_message(message, sender) {
        const element = document.createElement("div");
        element.className = "chat-message";

        let footer = "";
        if (sender === "{{ user.username }}" ) {
            element.className += " me";
        }
        else if (sender) {
            footer = ` from ${sender}`;
        }

        const wrapper = document.createElement("div");
        wrapper.textContent = message + footer;
        element.appendChild(wrapper);

        this.chat_messages_tag.appendChild(element);
        this.chat_messages_tag.scrollTop = this.chat_messages_tag.scrollHeight;

    },
    onsubmit(event) {
        event.preventDefault();

        const form_data = new FormData(event.target);
        const props = Object.fromEntries(form_data);
        event.target.reset();  // reset form

        const { message } = props;
        console.log("웹소켓으로 전송할 메세지 :", message);

        // this.append_message(message);

        this.ws.send(JSON.stringify({
            type: "chat.message",
            message: message,
        }))
    },
    update_user_list() {
        const html = [...this.username_set]
            .map(username => `<li>${username}</li>`)
            .join('');
        document.querySelector("#user_list").innerHTML = html;

        document.querySelector("#user_count").textContent =
            `(${this.username_set.size}명)`;
    },
    modal(message, ok_handler) {
        const modal_ele = document.querySelector("#staticBackdrop");
        const body_ele = modal_ele.querySelector(".modal-body");
        const button_ele = modal_ele.querySelector(".modal-footer button");

        body_ele.textContent = message;

        button_ele.addEventListener("click", () => {
            if(ok_handler) ok_handler();
            modal.hide();
        });

        const modal = new bootstrap.Modal(modal_ele);
        modal.show();
    }
};

handlers.init();

const protocol = location.protocol === "http:" ? "ws:" : "wss:";
const ws_url = protocol + "//" + location.host + "/ws" + location.pathname;
handlers.connect(ws_url);
</script>
{% endblock %}

chat/templates/chat/room_confirm_delete.html
{% extends "chat/base.html" %}

{% block content %}
    <h2>{{ room.name }} 삭제하기</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="alert alert-danger">삭제하시겠습니까?</div>
        <input type="submit" class="btn btn-danger" value="삭제하겠습니다." />
    </form>
{% endblock %}

chat/templates/chat/room_form.html
{% extends "chat/base.html" %}
{% load django_bootstrap5 %}

{% block content %}
    <h2>새 채팅방 만들기</h2>
    
    <div class="my-3">
        <form action="" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="만들기" class="btn btn-primary" />
        </form>
    </div>
    <a href="{% url 'chat:index' %}" class="btn btn-primary">
        대기실로 이동
    </a>
{% endblock %}